sources/bloodhound/customqueries.json

Dirk-jan proposed on his new research blog post (Abusing forgotten permissions on computer objects in Active Directory), two queries to find AddAllowedToAct rights on computers. I decided to add these queries on the "A one-man wolf pack" category as it represents groups (mainly). 
By the way, the feature is present in version 1.3.0 of BloodHound.py.
Query 1: Groups or users with the AddAllowedToAct right on a computer
Query 2: Exploitable cases from any authenticated user with the AddAllowedToAct right on a computer
TL;DR: if you have the AddAllowedToAct right on a computer, you can configure RBCD on it.

Adding custom BloodHound queries

---

ad.dockerfile
sources/zsh/history

Pull up, 
During internal testing we regularly need to break passwords, either database or NTLM hashes to taunt users 
In any case I think it is relevant to have a suite of tools like john and hashcat available on the AD image
Currently john is only available in the full version, personally I mainly use the AD image soo.. :)
By the way, I think it's a good idea to separate the repo's, I think it's cleaner!

[Ad Image] - Add John and hashcat

---

sources/bloodhound/customqueries.json

I've made a PR (#48) about queries allowing you to find when there's a 'AllowedToActOnBehalfOfOtherIdentity' right on a computer.
I'm guessing Dirk-jan modified his edge from 'AddAllowedToAct' to 'WriteAccountRestrictions' in part due to his PR for SharpHound (https://github.com/BloodHoundAD/SharpHoundCommon/pull/34).
Old queries (that are still present in his blog) won't work, therefore I'm adding the modified version.

Update custom BloodHound queries

---

sources/trilium/config.ini

Trilium is using the default `exegol4thewin` password and exposing it on all the interfaces.
I believe that is a security concern and that the service should only be exposed on `localhost` by default.

Change Trilium binding address to localhost

---

sources/install.sh
sources/zsh/history

Bug fix on the install_starkiller function that prevented the docker image to build properly 
New tools with example commands in history file:
- goshs, A simple web server which makes easy to upload or download from the network[goshs](https://github.com/patrickhener/goshs)
- gowitness, A web screenshot utility [gowitness](https://github.com/sensepost/gowitness)
- sslyze, A TLS/SSL scanning tool [sslyze](https://github.com/nabla-c0d3/sslyze)

install_starkiller bug fix and new tools added (goshs, gowitness, sslyze)

---

sources/install.sh

It seems that windapsearch and starkiller were not correctly installed. Here is the fix :)

Fix windapsearch

---

sources/zsh/history.d/impacket

typo in impacket's history for rbcd.py

---

sources/install.sh

The installed version of Ruby Nokogiri is in conflict between wpscan and cewl, version 1.11.4 corresponds to both requirements. So I uncomment the installation of cewl , add test for cewl and change the installed version of nokogiri.
Conflict: 
The fix :
This may break other tools, I will see on the pipeline if this case happen.

Fix ruby nokogiri

---

sources/install.sh
sources/zsh/history.d/tls-map

add https://github.com/noraj/tls-map / https://github.com/noraj/tls-map
N/A
N/A

add tls map

---

sources/install.sh

The problem of installing the kerbrute tool for ARM is solved. It is now compiled directly from Go and not static.

Troubleshooting kerbrute installation (AMD + ARM)

---

sources/zsh/history.d/pywsus

The Sysinternals folder has been has been moved from /opt/resources/windows/sysinternals/ to /opt/resources/windows/SysinternalsSuite/.
This commit reflects this change in the history file of the pywsus tool.

Fix pywsus history command

---

sources/install.sh
sources/zsh/aliases.d/soapui

Adds the SoapUI tool, a nice tool to debug / pentest SOAP Webservices.
It can parse WSDL files to create and execute base requests, and can also be proxied through Burp for deeper testing.
The test command is not the SoapUI executable, but another tool in the package.
The main command has no parameters to only show version/help and quit.
The tool size is 140MB.

Add SoapUI tool

---

sources/install.sh
sources/zsh/history.d/netdiscover

`Netdiscover is an active/passive address reconnaissance tool, mainly developed for those wireless networks without dhcp server, when you are wardriving. It can be also used on hub/switched networks.`
https://www.kali.org/tools/netdiscover/
This tool allows the user to passively scan the network by listening for ARP frames.
It can also act actively by sending ARP packages to private IP ranges.
The output is a nice table showing the IP / Mac address and MAC Vendor of the identified hosts.

Add Netdiscover Tool

---

sources/install.sh

The `cargo path` was missing in the `PATH` variable during `CrackMapExec` install. `Aardwolf` dependency needs it for its installation.
https://github.com/ThePorgs/Exegol-images/actions/runs/4335532241
https://github.com/ThePorgs/Exegol-images/pull/112

Fix CrackMapExec broken install - Rustc - Cargo PATH

---

sources/exegol/load_supported_setups.sh
sources/exegol/skel/firefox/addons.txt
sources/firefox/requirements.txt
sources/firefox/setup.py
sources/firefox/user-setup.py
sources/install.sh

Firefox customization now works as announced in PR #107. 🦊 
Also, the user is now able to add his favourites addons to each new container with my-resources by two ways.
It is possible to create a list in ~/.exegol/my-resources/setup/firefox/addons.txt with the links in Mozilla's addon shop :
> The last versions of the addons will then be downloaded and installed automatically.
It is also possible to directly add .xpi files in the folder ~/.exegol/my-resources/setup/firefox/addons :
> The addons will then be installed from local .xpi files.
**Note** : both way can be used *simultaneously* by just creating the addons.txt and the addons folder.

Fixed Firefox customization issue and added support for addons in my-resources

---

sources/install.sh

The amass install URL seems to have changed from `github.com/OWASP/Amass/v3/...@master` to `github.com/owasp-amass/amass/v3/...@master`
https://github.com/ThePorgs/Exegol-images/actions/runs/4667149750/jobs/8270118394?pr=129
https://github.com/ThePorgs/Exegol-images/actions/runs/4682060823/jobs/8322882477?pr=135

Fix amass installation

---

sources/assets/zsh/history.d/joomscan
sources/install/package_web.sh

Fix joomscan installation.
JoomScan is an open source project, developed with the aim of automating the task of vulnerability detection and reliability assurance in Joomla CMS deployments. 
https://github.com/ThePorgs/Exegol-images/actions/runs/3557732633/jobs/5977150292

Fix - joomscan

---

sources/assets/zsh/aliases.d/peepdf
sources/install/package_forensic.sh

New tool - Peepdf

---

sources/assets/zsh/aliases.d/trilium

Fixed trillium tool starting issue after authentication.
The environment variable `TRILIUM_ENV=dev` was missing in the alias.
Once logged in, the service fails to load the `desktop.js` resource.
On the official Trillium github repository, the tool is started with this environment variable :
https://github.com/zadam/trilium/blob/stable/package.json

Fix - trilium loading desktop.js resource

---

sources/assets/bloodhound/customqueries.json

The query **Kerberoastable users and where they are AdminTo** was invalid as it was returning the variable **u** and using the variable **u1**.
The variable was renamed to **u** to keep consistency with other queries

Fix variable in bloodhound custom query

---

sources/install/package_ad.sh

Hello,
as already reported to [upstream](https://github.com/OPENCYBER-FR/RustHound/pull/17/commits/110a6c1aaf51336c6b4b04d1e898f41e42c7772b), the dependency `libclang-dev` is pulled twice for `Rusthound`.
Removing one for cleaning up.

Rusthound: remove the duplicated dependency libclang-dev

---

sources/install/package_ad.sh
sources/install/package_base.sh
sources/install/package_code_analysis.sh
sources/install/package_crypto.sh
sources/install/package_forensic.sh
sources/install/package_network.sh
sources/install/package_osint.sh
sources/install/package_reverse.sh
sources/install/package_rfid.sh
sources/install/package_web.sh
sources/install/package_wifi.sh
sources/install/package_wordlists.sh

Hello,
as discussed in https://github.com/ThePorgs/Exegol-images/pull/159, this PR is to remove all --depth=1, as the manual states a whitespace between the word depth and the digit.
```
man git-clone
--depth <depth>
Create a shallow clone with a history truncated to the specified number of commits. Implies --single-branch unless --no-single-branch is given to fetch the histories near the tips of all branches. If you want to clone
submodules shallowly, also pass --shallow-submodules.
```
CC @QU35T-code for review

Replace all git clone --depth=1 by --depth 1 for compliance

---

sources/assets/zsh/aliases

When doing an assessment, I found it painful to regularly have to type `cd /workspace`.
I ended up adding a simple zsh alias: `ws`
The goal was for the alias to be as simple as `cd`.
Unless there is another trick to efficiently go back to the workspace folder, I thought maybe other users would appreciate this simple contribution.

Add zsh alias 'ws' to quickly change directory to the workspace

---

sources/install/package_ad.sh

Remove the dependencies used while compiling rusthound. Once the binary has been built these dependencies are not longer used.
Cleaning these two folders would free 729M of disk usage.

Clean rusthound

---

Dockerfile
ad.dockerfile
debug.dockerfile
light.dockerfile
osint.dockerfile
web.dockerfile

1/ As mentionned in https://github.com/ThePorgs/Exegol-images/issues/96, this PR aims at reducing the number of layers of the Docker images for better performance, reduced image size and to remove potential caching quirks. To do so, the RUN calls are merged into one as recommended by [Docker best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/).
For example, the released image full-3.0.2 has 28 layers. By reducing it to 4 layers, the new image is 0.9GB smaller.
2/ In addition, the image is based from `debian:11-slim` rather than `debian:11`. Any extra necessary packages to build the image will be pulled from Debian's repositories anyway.
3/ Finally, the apt cache files are removed from the image. There is no need to ship an image with outdated package …

Reduce Docker layers

---

sources/assets/exegol/load_supported_setups.sh

In the unlikely event that a temporary bqm file exists prior to running the tool itself, this PR removes the tempfile.
I don't think this case should ever happen, but better safe than sorry.

[my-resources] Remove any bqm temporary file for Bloodhound

---

sources/assets/zsh/zshrc

Whenever I am in the middle of a command line and I find out that I am missing a piece, I like commenting the line, to easily come back to it later.
However, the way zsh currently behaves completely hides the command as it is basically black on black.
The image below shows how "This is a comment" is displayed (hint: it's written on the first line):
This PR makes the same comment appear as follows:
At least we can read something.
This PR is minor and is a customization I have in my-resources, I thought maybe it can be of interest of others.
PR is based on the branch 3.1.1.

Remove zsh color for comments

---

sources/install/package_c2.sh

```bash
> # pwncat-cs -lp 9001
/root/.local/pipx/venvs/pwncat-cs/lib/python3.9/site-packages/paramiko/transport.py:178: CryptographyDeprecationWarning: Blowfish has been deprecated
'class': algorithms.Blowfish,
[20:16:25] Welcome to pwncat 🐈!
```
https://github.com/paramiko/paramiko/issues/2038

Fix pwncat-cs warning - Blowfish has been deprecated

---

sources/assets/zsh/history.d/rustscan
sources/install/package_network.sh

Hello,
this PR aims at adding the tool RustScan to the base image.
I was not sure about the sourcing, but I left it as is.
This code is actually inspired from the function install_rusthound.
Cheers

Add the tool RustScan

---

sources/install/package_base.sh

In a firewalled environment I ran into the following error:
```text
[EXEGOL] Adding build pipeline test command: cargo --version
[EXEGOL] Installing rvm
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: keyserver receive failed: Connection timed out
```
Using port 80 makes it possible to build the image behind a firewall.
Feel free to close this, if you think it is unnecessary.

Use port 80 to connect to gpg keyservers

---

debug.dockerfile
sources/assets/exegol/load_supported_setups.sh
sources/install/common.sh
sources/install/package_ad.sh
sources/install/package_base.sh
sources/install/package_c2.sh
sources/install/package_cloud.sh
sources/install/package_code_analysis.sh
sources/install/package_cracking.sh
sources/install/package_crypto.sh
sources/install/package_forensic.sh
sources/install/package_misc.sh
sources/install/package_mobile.sh
sources/install/package_network.sh
sources/install/package_osint.sh
sources/install/package_reverse.sh
sources/install/package_rfid.sh
sources/install/package_sdr.sh
sources/install/package_steganography.sh
sources/install/package_voip.sh
sources/install/package_web.sh
sources/install/package_wifi.sh

During a build, some commands sometimes fetch things online (e.g. curl, wget, apt, git, go, git, etc.).
If a random network issue occurs and makes that commands fail, the whole build will be discarded as one tool will fail unit test.
In order to counter that, those commands will be retried every X seconds, X being exponentially bigger after each retry.

Attempting to fix random network issues when building

---

sources/install/package_rfid.sh

fix typo in proxmark

---

sources/assets/exegol/load_supported_setups.sh

As reported in https://github.com/ThePorgs/Exegol-images/issues/207, this PR fixes the issue introduced when the variables were renamed from lowercase to uppercase.
One of the variable was `path` and declared in a function, hence renaming to PATH overrode the environment variable.
This PR:
- fixes the issue by renaming the PATH variable to lpath
- all local variables are now explicitely scoped with the `local` keyword, and renamed in lowercase, leaving the UPPERCASE variable to ones with a global scope
- all local variables start with the lowercase letter `l`
- single square brackets removed by double square brackets to avoid any issues.

Fix load supported setups

---

sources/assets/zsh/aliases.d/nmap-parse-output
sources/assets/zsh/history.d/nmap-parse-output
sources/install/package_network.sh

New tool nmap-parse-output to parse XML output of nmap (`nmap -oX file.xml`).
- Not sure if the test command works as expected. Otherwise `which nmap-parse-output` could also be used. `grep` is used to look for the version number and it fails if it's not in the output.
- The tool also provides shell completions (https://github.com/ernw/nmap-parse-output?tab=readme-ov-file#zsh-completion). I am not sure how this can and should be added to the image.

nmap-parse-output

---

.github/workflows/entrypoint_pr.yml
sources/install/package_ad.sh
sources/install/package_cloud.sh
sources/install/package_crypto.sh
sources/install/package_forensic.sh
sources/install/package_network.sh
sources/install/package_osint.sh
sources/install/package_reverse.sh
sources/install/package_rfid.sh
sources/install/package_web.sh
sources/install/package_wifi.sh

When installing deps through a venv, the `./venv/bin/python3` is not transparently made through CNR (Catch And Retry). Requires to prepend the command line with the CNR like: `catch_and_retry ./venv/bin/python -m pip install deps ...`
Would be better to do this:
```bash
cd /path/to/tool || exit
source ./venv/bin/activate
pip3 install -r ./requirements.txt
deactivate
```
`pip2/pip3` are transparently handled through CNR.

Refacto pip installs CNR

---

sources/assets/exegol/load_supported_setups.sh

1/ BloodHound customqueries for `my-resources` was broken again after moving the `source` command into a function. The end result was that the `bqm` executable could not be found.
2/ In the process, I found and fixed another regression (which I introduced) when BloodHound customqueries files are both in the directories `merge` and `replacement`.
Fix tested with success.

load_supported_setups: fix bqm not found, and BloodHound customqueries

---

sources/assets/zsh/aliases.d/fzf
sources/assets/zsh/history.d/hashcat
sources/assets/zsh/zshrc

Add a an `fzf-haiti` command to search for hash type, for example while using `hashcat`.
Run a `hashcat` crack:
Choose a hash mode using `fzf`:
Choose the wordlist using `fzf`:
N / A
I know `hashcat` automatically select hash type when he can decide, but this doesn't work for a lot of hash type that looks the same.

Added an fzf-haiti command

---

sources/assets/zsh/history.d/cewler
sources/install/package_wordlists.sh

Adding [cewler](https://github.com/roys/cewler), a Python alternative to [cewl](https://github.com/digininja/CeWL)
Putting the PR on hold for now, as the tool raises an issue when used (https://github.com/roys/cewler/issues/1)

Adding cewler

---

sources/install/package_cracking.sh

Fix 7zip2john
Before :
```
> 7z2john.pl 
Can't locate Compress/Raw/Lzma.pm in @INC (you may need to install the Compress::Raw::Lzma module) (@INC contains: /etc/perl /usr/local/lib/aarch64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/aarch64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/aarch64-linux-gnu/perl-base /usr/lib/aarch64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at /opt/tools/john/run/7z2john.pl line 6.
BEGIN failed--compilation aborted at /opt/tools/john/run/7z2john.pl line 6.
```
Now :
```
> 7z2john.pl       
Usage: /opt/tools/john/run/7z2john.pl <7-Zip file>...
```

Fix 7zip2john

---

sources/assets/bloodhound/customqueries.json

Updated the custom query "Can a user from domain ‘A‘ do anything to any computer in domain ‘B’ (Warning: VERY Heavy)", which was not working.
Changes made :
- Save the user's intermediate selections by concatenating them into a string
- Split the string in the last query to extract the different selections
_Edit : There is probably a better way of doing it, at least it works now_ :grin:

Updated custom query for cross domain rights.

---

sources/assets/bloodhound/customqueries.json

> Added Bloodhound Custom Queries for ESC9. Taken from [https://github.com/ly4k/Certipy/blob/main/customqueries.json#L185-L214](https://github.com/ly4k/Certipy/blob/main/customqueries.json#L185-L214
)

Added Bloodhound Custom Queries for ESC9

---

sources/assets/bloodhound/customqueries.json

There was an issue with find shortest path when some computers objects where also users objects.
Added a WHERE clause to avoid these cases.

Added WHERE clause to avoid errors on query.

---

sources/assets/exegol/load_supported_setups.sh

Fixed typo in the find command as discussed with @ShutdownRepo

Fixed typo in find command.

---

sources/assets/bloodhound/customqueries.json

This PR adds a new category for Bloodhound customqueries: `Weak ACLs`, with new queries to spot ACLs of interest.
I also moved some queries from other categories which were dealing with ACLs as well.
And, I added another query to spot users of high value groups who are neither members of protected users nor marked as sensitive. There is a similar query but the outcome is different and easier to use in my opinion.

Add some Bloodhound custom queries

---

sources/install/package_base.sh

If `$listening_processes` holds multiple ids, quoting them leads to them being passed to `kill` as one argument instead of multiple.

fix: allow the shell to split arguments to kill

---

sources/install/package_ad.sh

https://github.com/lgandx/Responder/pull/249 and https://github.com/lgandx/Responder/pull/250 were both merged.

fix(ad): remove Responder PRs because they were merged

---

sources/assets/shells/history.d/legba
sources/install/package_network.sh

I added the tool legba (https://github.com/evilsocket/legba) a login bruteforcer / password spraying written in Rust
No related issue.
I hope that everything is good :)

Adding legba (network bruteforcer)

---

sources/assets/bloodhound/customqueries.json

This PR adds a bunch of new customqueries for Bloodhound:
- Add a new category named `High Value Targets` to mark more groups and objects as HVT. There are other queries already present in the collection to mark objects such as Unconstrained objects as HVT, but I decided not to move them for clarity.
- In the Weak ACLs section, the filter on some destination Enabled objects is removed. A disabled object could indeed be interesting if the relation type is GenericAll.
- A few other misc queries
- An all-in-one query to add `indexes` to speed up queries execution time

Add new Bloodhound customqueries

---

sources/assets/shells/history.d/kerbrute

Add some commands to zsh history for Kerbrute and in particular the `user=pass` feature when password spraying.
I also replaced the `-d` flag by its `--domain` equivalent.

Add some commands to zsh_history for Kerbrute

---

sources/assets/shells/history.d/pretender
sources/install/package_ad.sh

Adding pretender to Exegol-Images

---

sources/assets/shells/aliases.d/_init

Add a systemctl alias to tell to use the service command
```bash
root@exegol-test /workspace # systemctl restart test
Systemctl cannot be used inside the container. Please use the "service" command instead.
```

Add systemctl alias

---

sources/assets/shells/aliases.d/evil-winrm
sources/install/package_ad.sh

The ruby version for evil-winrm has been downgraded (**3.2.2** to **3.1.2**) as a function is deprecated and no longer exists on a more recent version (SSL use)
https://www.reddit.com/r/ruby/comments/1196wti/psa_and_a_little_rant_fileexists_direxists/

Downgrade ruby version for evil-winrm (3.2.2 to 3.2.1)

---

sources/assets/exegol/load_supported_setups.sh

when creating tmux.conf on windows, \r\n will get added to EOL. This causes issues when tmux parses ~/.tmux.conf preventing you from being able to use TMUX. Adding dos2unix to convert the file so Tmux can properly parse file. 
N/A

Fix Tmux parse issues when conf is created on Windows.

---

sources/assets/patches/openssl.patch
sources/install/package_ad.sh
sources/install/package_base.sh

* Openssl configuration issue that prevents SSL use with evil-winrm.
* MD4 support
* https://forum.hackthebox.com/t/evil-winrm-error-on-connection-to-host/257342/9

OpenSSL activate legacy support

---

sources/install/package_ad.sh
sources/install/package_forensic.sh

Delete the temp fix because this patch fixes it #308

Remove temp fix (pycryptodome)

---

sources/assets/shells/zshrc

zsh autosuggestion does not work if TERM is screen. By default, tmux uses screen. If a user imports his tmux.conf config file, he won't get the autosuggestion. This fix forces the value of the TERM variable.
https://github.com/zsh-users/zsh-autosuggestions/issues/229

TERM variable added to zshrc file for tmux compatibility

---

sources/assets/bloodhound/customqueries.json

BHQ queries updates (by @ShutdownRepo)

Update BHQ queries

---

sources/assets/bloodhound/customqueries.json

This PR aims at improving the custom queries for Bloodhound.
To do so, I refactored many queries to:
- standardize a bit more the formatting while reducing the queries length
- improve the performance of queries by adding more criteria to reduce the set of nodes Neo4j must take into account when computing the results, the flag `enabled` is a typical example
- remove useless subqueries
- improve the regexp for the queries checking for plaintext password
- fix a bogus request
- one query was not doing what the comment said it would
- add more indexes
- add one nice query I wrote: Administrators and Domain/Entreprise Admins with sessions not on domain controllers

BloodHound customqueries: refacto for clarity, performance, fix and new queries

---

sources/assets/bloodhound/customqueries.json

Dear team,
I noticed that when querying Bloodhound to get a list of machines where Domain users can RDP to, it only lists the machines where the single node "domain users" has a _direct_ canRDP relationtype with the computer objects.
The existing query does not take into account that Domain Users can be member of a group, and it's this group that has a canRDP relationship with the computers.
This PR fixes that, and is basically the union of the builtin queries: `First Degree RDP Privileges` and `Group Delegated RDP Privileges`.
In addition:
- I added new queries to return paths from authenticated users->RDP->computers, with a distinction machines != servers.
- the case of some keywords were switched to uppercase for clarity.

Bloodhound customqueries: better RDP queries

---

sources/install/package_wifi.sh

Latest changes on [Pyrit](https://github.com/JPaulMora/Pyrit) broke the install. Install now fails with both python2 and python3. Using an old commit while it's not fixed upstream.

Temp fix for Pyrit install

---

.github/workflows/sub_code_check.yml
sources/code_compliance_check.py
sources/install/package_mobile.sh

Added an additional Check step to the pipeline.
This will analyze all the source code and retrieve the temp-fixes present in certain functions. If the temp-fix date has expired, then the CCC will return an error before the build even starts.
This will save time and avoid having to build to see that a temp-fix has expired and needs to be updated.

Improve CCC adding temp-fix check

---

sources/install/package_ad.sh
sources/install/package_base.sh
sources/install/package_c2.sh
sources/install/package_cracking.sh
sources/install/package_desktop.sh
sources/install/package_mobile.sh
sources/install/package_wifi.sh

I noticed that some tools missed the flag `--depth 1` for `git clone`.
For some tools, it was simply forgotten.
For others, the flag --depth 1 was removed for temp fixes reasons.
This PR reinstates the depth flag to clone directly the appropriate branch in a single command instead of doing a `git clone` followed by a `git checkout`:
- Example with sliver: `git -C /opt/tools/ clone --branch v1.5.41 --depth 1 https://github.com/BishopFox/sliver.git`
- Another with Bloodhound-CE: `git -C /opt/tools/ clone --branch bloodhound-ce --depth 1 https://github.com/dirkjanm/BloodHound.py BloodHound-CE.py`
About sliver, I moved the temp fix criticalecho at the beginning of the function to only clone the repo if the date condition is met. I hope it's ok like this.

Reduce image size by adding flag depth 1 when git cloning

---

.github/workflows/sub_export_tools.yml

This PR updates the pipeline so that the tools list exports are in 2 different files (AMD64 / ARM64) instead of just one.
This allows for a better display in the documentation:
https://github.com/ThePorgs/Exegol-docs/pull/47

Export of the tools list in separate files depending on the architecture

---

sources/install/package_c2.sh

Added `rex-text` dependency which is missing for metasploit's `pattern_create.rb` tool to work correctly.
https://github.com/ThePorgs/Exegol-images/issues/332

Add missing dep to metasploit

---

.github/workflows/sub_export_tools.yml
sources/install/package_ad.sh
sources/install/package_misc.sh

Removed commas from tool descriptions to prevent incorrect parsing of documentation CSVs.
Changed the pipeline check so that it returns 1 when it detects a comma in the tool description.

Remove commas from descriptions + fix pipeline

---

sources/install/package_web.sh

Hello,
sslscan is built statically, so there is no need to keep in the image the files generated when building it.
Before the PR:
```
du -hs /opt/tools/* | grep sslscan
220M	/opt/tools/sslscan
```
After the PR:
```
du -hs /opt/tools/* | grep sslscan
980K	/opt/tools/sslscan
```

Reduce image size by removing sslscan build files

---

sources/assets/shells/history.d/nuclei

Modify the `nuclei` history file so nobody scan `example.com` by mistake and also to match other history regarding the `$TARGET` variable.
N / A
N / A

Update nuclei history

---

sources/assets/shells/aliases.d/binwalk
sources/install/package_forensic.sh

Greetings,
When running something along the line of: `binwalk -e test.sqhfs --run-as=root`, I get:
```
WARNING: Extractor.execute failed to run external extractor 'unsquashfs -d 'squashfs-root' '%e'': [Errno 2] No such file or directory: 'unsquashfs', 'unsquashfs -d 'squashfs-root' '%e'' might not be installed correctly
```
The `unsquashfs` dependency is not installed, this PR aim to fix that, it also move the binwalk install in it's own install function.
N/A
Binwalk list other dependency such as `sasquatch` (https://github.com/ReFirmLabs/binwalk/blob/master/INSTALL.md), since I haven't encountered a case where those were needed I propose to add them later on if necessary.

Fix binwalk dependencies

---

sources/assets/bloodhound/customqueries.json

This PR fixes a typo in a custom query for Bloodhound.

Fix typo in a Bloodhound custom query

---

sources/assets/shells/aliases.d/pyrit
sources/install/package_wifi.sh

This PR moves the pyrit tool instead of making an alias/symlink so Wifite can detect and use it.
https://github.com/ThePorgs/Development/issues/183

Move pyrit into the PATH

---

sources/assets/shells/history.d/jsluice
sources/install/package_web.sh

This PR adds the jsluice tool.

Add jsluice

---

sources/assets/shells/history.d/impacket

Hello,
This PR is to reorganize the history of impacket's commands to group them by tool.
It also adds sometimes the flag -no-smb-server when redirecting to LDAP, and instead adds --http-port.

Reorganize impacket history

---

sources/assets/bloodhound/customqueries.json

Hello,
this PR modifies some Bloodhound custom queries.
- Outdated OS:
Instead of returning every outdated computers referenced in the AD, only return the ones which machine account is enabled.
Indeed, returning a disabled Windows XP is not interesting.
- Top 10 user sessions:
The queries were returning the top 10 users with local admin rights. So basically, it was also returning the domain administrators with admin rights on all object computers including the domain controllers. And if the domain has more than 10 DA, then these are the only ones returned.
The modified queries only return the top 10 users who are neither Domain Admins, Enterprise Admins, nor Administrators.
- Misc:
Fix a broken query and an english typo

Bloodhound queries: improve outdated OS and top 10 users queries and misc fixes

---

sources/assets/shells/aliases.d/responder

Responder configuration has been updated (<https://github.com/lgandx/Responder/commit/807bd57a96337ab77f2fff50729a6eb229e5dc37>).
The current `sed` command no longer matches the new configuration file.
I've added a regex with spaces to make this version backwards-compatible.
I tested it on the latest version of nightly and the new alias works well.
Before :
After :

Fixed a bug allowing configuration updates following Responder update

---

sources/assets/bloodhound/customqueries.json

* Updating 2 Bloodhound custom queries used to find Tier 0 objects in the AD to search in a broader way.
* Adding a new Bloodhound custom query to find enabled Tier 0 computers based on their Service Principal Names (SPNs). Useful when you are looking for backup servers located in the domain which have random computer names and/or descriptions.
I forgot to sign the commits in my previous PR #384...
The words used in the new query which parses SPNs could be tailored more accurately. I do not have enough Bloodhound data for now to offer a more accurate filter. Feel free to change it with your own list during your internal assessments.

Modified BH customqueries to find T0 assets

---

sources/assets/bloodhound/customqueries.json

Hello,
This PR improves custom queries for BloodHound.
In details:
- Improved query "Logged in Admins" to actually return the information of where an admin has a session. The link between the admin and the computer was lost.
- Reworked query "Users with local admin rights" to not return Domain/Enterprise admins
- Added new query "Enabled users (not Domain/Enterprise Admins) with ReadLAPSPassword rights"
- Improved RDP queries to make them shorter with the use of the function shortestPath() instead of UNION
- Modified some queries some that 'c' is the variable for Computers, u for User, etc. to align with the rest of the queries

BloodHound: Add a new query to list users who can ReadLAPSPassword and improve other queries

---

sources/install/package_ad.sh

The current bloodhound-ce installation is broken. The collectors page returns the following errors
In fact, no Azurehound collectors is found. Bloodhound-ce expect the Azurehound and Sharphound archive to follow a nomenclature: https://github.com/SpecterOps/BloodHound/blob/403c45c041f36c2e80db6c5922f298ee6484fff8/cmd/api/src/api/v2/collectors.go#L32 
The version should be in the named of the archive (i.e: SharpHound-v2.4.1.zip). This PR fix this issue by retrieving the azurehound version and creating an archive with the arm and amd binary

Fix bloodhound-ce collectors

---

sources/assets/shells/history.d/adminer

> fix adminer history
AD-miner tool is connected to Neo4j.
The $USER and $PASSWORD variables are used for Active Directory accounts from the "profile.sh" script.

fix adminer

---

sources/assets/shells/history.d/autobloody
sources/install/package_ad.sh

New tool [autobloody](https://github.com/CravateRouge/autobloody/), which allows to automatically exploit AD attack paths detected by Bloodhound. Related to [bloodyAD](https://github.com/CravateRouge/bloodyAD).

feat: new tool autobloody

---

sources/install/package_ad.sh

Howdy,
this PR aims at improving the installation of the ingestors Sharphound and Azurehound for Bloodhound-CE:
- the case of local variables is switched from uppercase to lowercase for consistency across Exegol
- local paths are put into a variable instead of repeating each time the same paths
- instead of Curling the same Github page several times, the result is put once into a `temporary file`
- instead of `Grepping` the json output of Github, the temporary file is parsed with `jq`
- fix the variable `azurehound_url_amd64` that was containing the `arm64` URL, and the other way around the arm64 variable contained the amd64 URL
- A sha256 file was computed locally but nothing was done with it. Instead, the sha256files for Azurehound are downloaded from Github and the integrity of the zip …

Improve Sharphound and Azurehound installations

---

sources/assets/firefox/setup.py

- Just a simple PR that add firefox multi-account containers to exegol this will surely save time and no need of using foxyproxy that uses entire firefox windows
- Add useful bookmarks (rootme-org and rev shell generator)

evol: added bookmarks and extension in firefox

---

sources/assets/shells/history.d/smbclient-ng

This PR aims to fix the arguments of `smbclient-ng`, the `--target` switch has changed to `--host`.
N / A
N / A

Update smbclient-ng history

---

sources/assets/bloodhound/customqueries.json

This PR aims at improving a few bloodhound custom queries dealing with the detection of privileged users that one can pick to impersonate (S4U2Self abuse, RBCD).
In particular, it deals with the special case of the RID 500 Administrator group as per the following blog post:
https://sensepost.com/blog/2023/protected-users-you-thought-you-were-safe-uh/
In details, it returns as an impersonation candidate the RID 500 Administrator account when it is not marked `sensitive and cannot be delegated`, even if the account is a member of the group `Protected Users`.
In addition, one query that was listing accounts to impersonate from the DA, EA and Administrator groups was expanded to include additional interesting built-in groups. Some of them also allows to log on for instance.

BH Customqueries: add detection for RID 500 administrator impersonation and more

---

sources/install/package_misc.sh

When building the light image, the function `install_cyberchef` is ran twice because the light image run `package_most_used` AND `package_misc`. Thus if the `mkdir` call has not a `-p` argument, the image building fails because the directory already exist.
N / A
N / A

Added a -p argument to the mkdir in the Cyberchef install

---

sources/install/package_c2.sh

This PR aims to add the PEASS ruby module ot MSF (https://github.com/peass-ng/PEASS-ng/tree/master/metasploit).
Fixes #433.
N / A

Added the PEASS Ruby module for MSF

---

sources/install/package_ad.sh

The project ROADtools actually consists of multiple packages. This renames ROADtools to roadrecon and adds roadtx (a tool to play with Azure Tokens)

fix(ad): rename roadtools to roadrecon and add roadtx

---

sources/assets/bloodhound/customqueries.json

Two queries based on shortestPath() were not working as the explicit check `source <> destination` was missing. This PR fixes that and adds the explicit check for all the queries using this function, even the ones where Bloodhound was not returning an error on my dataset.
Also modifies a bit the interesting groups where users to impersonate could be members of.

BH customqueries: fix queries based on shortestPath

---

sources/assets/exegol/build_pipeline_tests/run_tests.py

Because the #464' `zap -suppinfo` test has timed out [here](https://github.com/ThePorgs/Exegol-images/actions/runs/13739604811/job/38430191880?pr=464#step:4:447).
In fact, this test (and zed) is really slow: 15 seconds on my computer (which I consider quite powerful):
```
[Mar 08, 2025 - 21:31:29 (UTC)] 3738b929bf54 /workspace # time zap -suppinfo
[SNIP...]
real	0m15.686s
user	0m17.295s
sys	0m1.243s
[Mar 08, 2025 - 21:32:40 (UTC)] 3738b929bf54 /workspace # time zap -help
[SNIP...]
real	0m14.413s
user	0m18.187s
sys	0m0.943s
```
This test, which is already slow, combined with other tests running in parallel, could fail the pipeline even though it's just slow (like the example I mentioned above). I think it would be a good idea to slightly increase the timeout threshold and avoid wasting a …

Increasing the timeout threshold

---

sources/assets/shells/aliases.d/bettercap
sources/install/package_wifi.sh

I was inspired by what was done for ruler:
https://github.com/ThePorgs/Exegol-images/blob/7d7bf085cc86eb9e03f0cb0a3007045a4647d2ff/sources/install/package_ad.sh#L341-L346

Using higher Go version for bettercap install

---

sources/assets/shells/.curlrc
sources/assets/shells/wgetrc
sources/install/common.sh
sources/install/package_cloud.sh
sources/install/package_reverse.sh

#458 fails first because of `upx`, and now because of `BloodHound` because curl never ever retried when guthub is rate-limited, here my fix using a `.curlrc` to make it globally available :)
Before:
```
[EXEGOL] Installing BloodHound-CE
[SNIP...]
[EXEGOL] Catch & retry function for: curl
[EXEGOL DEBUG] sh -c "curl --location --silent https://api.github.com/repos/SpecterOps/BloodHound/releases -o /tmp/tmp.84z9GSOOkf "
jq: error (at /tmp/tmp.84z9GSOOkf:1): Cannot index string with string "tag_name"
The command '/bin/sh -c ./entrypoint.sh ${FUNCTION}' returned a non-zero code: 5
```
After:
```
[EXEGOL] Installing BloodHound-CE
[SNIP...]
[EXEGOL] Catch & retry function for: curl
[EXEGOL DEBUG] sh -c "curl --location --silent https://api.github.com/repos/SpecterOps/BloodHound/releases -o …
```

fix: curl never ever retried + reduce verbose

---

sources/install/package_forensic.sh

Running `volatility3 -vv` show that some modules cannot be used because the dependecies are not installed:
```
Volatility 3 Framework 2.24.0
INFO     volatility3.cli: Volatility plugins path: ['/root/.local/share/pipx/venvs/volatility3/lib/python3.11/site-packages/volatility3/plugins', '/root/.local/share/pipx/venvs/volatility3/lib/python3.11/site-packages/volatility3/framework/plugins']
INFO     volatility3.cli: Volatility symbols path: ['/root/.local/share/pipx/venvs/volatility3/lib/python3.11/site-packages/volatility3/symbols', '/root/.local/share/pipx/venvs/volatility3/lib/python3.11/site-packages/volatility3/framework/symbols']
INFO     volatility3.plugins.yarascan: Neither yara-x nor yara-python (>3.8.0) module not found, plugin (and dependent plugins) not available
DEBUG …
```

Fixed optional dependencies for volatility3
