- sources/install.sh
- sources/zsh/aliases
I really like your tools, but I think the IDA reverse engineering tool is missing.
I don't know if it's necessary or not but I would like to propose you my pull request.
Sincerely,
Lucien
> Adding ida reverse engineering tool

- Dockerfile
- ad.dockerfile
- light.dockerfile
- osint.dockerfile
- sources/install.sh
- sources/zsh/aliases
- sources/zsh/history
- web.dockerfile
- fixing #3
- fixing #4
- fixing #5
- added ida (#7)
- minor updates and fixes
> Release 2.0.2

- sources/install.sh
- sources/zsh/history
Hey!
I added some useful tools for bugbounty, pentest:
- Anew (https://github.com/tomnomnom/anew) : this is a tool for adding new lines to files, skipping duplicates.
- Naabu (https://github.com/projectdiscovery/naabu) : a fast port scanner
I also fixed the installation of httpx project discovery (https://github.com/projectdiscovery/httpx)
> Adding httpx, anew, naabu

- sources/install.sh
- sources/zsh/aliases
- sources/zsh/history
Installing DFScoerce.py + add usage to history
References:
- https://github.com/Wh04m1001/DFSCoerce
- https://www.thehacker.recipes/ad/movement/mitm-and-coerced-authentications/ms-dfsnm
> Add dfscoerce.py

- sources/install.sh
Fixing python dependencies for empire following the PR #31 relative to issue #29
> Empire: fixing python dependencies

- sources/install.sh
- sources/zsh/history
"A tool to quickly bruteforce and enumerate valid Active Directory accounts through Kerberos Pre-Authentication"
https://github.com/ropnop/kerbrute
> Add kerbrute

- sources/install.sh
Hello there ! 
Adding awesome gf (powerfull grep wrapper) to exegol
- https://github.com/tomnomnom/gf
- https://github.com/1ndianl33t/Gf-Patterns
> Adding Gf by Tomnomnom and Gf patterns by 1ndianl33t

- sources/install.sh
I Split the installation of Ghunt and google-chrome. Ghunt is still commented and on FIXME status.
> Fixing google chrome installation

- .github/workflows/sub_release_manifest.yml
"Release (all tags) workflow was raising a unexpected EOF error because of a missing ".
> Fixing release workflow

- sources/install.sh
- sources/zsh/history.d/ctf-party
add https://github.com/noraj/ctf-party / https://noraj.github.io/ctf-party/
N/A
N/A
> add ctf-party

- sources/install.sh
Updated the minikerberos dependency to its latest version.
The issue with the `minikerberos` dependency is resolved :
https://github.com/skelsec/pypykatz/issues/117
> Pypykatz - Update minikerberos version

- sources/install.sh
- sources/zsh/history.d/notify
Tool requested by @ShutdownRepo :)
> New tool - Notify

- sources/assets/zsh/history.d/trevorspray
- sources/install/package_osint.sh
Added new requested tool : trevorspray
TREVORspray is a modular password sprayer with threading, SSH proxying, loot modules, and more!
https://github.com/blacklanternsecurity/TREVORspray/pull/27
> New tool - trevorspray

- sources/install/package_osint.sh
FIx buster installation.
An advanced tool for email reconnaissance
> Fix - buster

- sources/assets/zsh/aliases.d/spiderfoot
- sources/install/package_osint.sh
Fix spiderfoot installation.
SpiderFoot automates OSINT collection.
> Fix - spiderfoot

- sources/assets/zsh/history.d/ligolo-ng
- sources/install/package_network.sh
New tool : Ligolo-ng
An advanced, yet simple, tunneling tool that uses a TUN interface.
Agents have also been added to be accessible in resources : https://github.com/ThePorgs/Exegol-resources/pull/9/files
https://github.com/nicocha30/ligolo-ng/issues/32
> New tool - ligolo-ng

- sources/install/package_web.sh
> Fix - phpggc

- sources/install/package_most_used.sh
Quick fix apt tools installation for most used package
> Fixed package most used apt tools installation

- sources/assets/crackmapexec/cme.conf
- sources/install/package_ad.sh
CME is now located on https://github.com/mpgn/CrackMapExec
> Update to the new repository of CME

- sources/assets/zsh/history.d/scrcpy
- sources/install/package_mobile.sh
Add [`scrcpy`](https://github.com/Genymobile/scrcpy) to the selection of mobile tools
> add scrcpy to mobile tools

- sources/install/package_base.sh
> Add sqlite3

- sources/install/package_most_used.sh
- sources/install/package_web.sh
Removed apt install
Added git clone
This is my first PR. I'm afraid of breaking something... Please be indulgent.
> Sqlmap (latest) install from git

- sources/install/package_base.sh
- sources/install/package_c2.sh
* Update fzf with git installation
* Fix fzf bindings (CTRL + R + CTRL + T)
> Fix binding and update fzf

- ad.dockerfile
> Fix broken dockerfile

- light.dockerfile
- sources/assets/zsh/aliases.d/responder
- sources/install/package_ad.sh
- sources/install/package_base.sh
- sources/install/package_cloud.sh
* Add configure_john in the light dockerfile
* Create python venv for responder
* Install libwww-perl to the package_base
* Install wheel dep for the cloudmapper tool
* Add 2 tests for runfinger and multirelay
> Preparing the release 3.1.0

- sources/assets/zsh/aliases.d/crackmapexec
> Fix cme alias

- .github/workflows/entrypoint_pull_request.yml
- sources/assets/bloodhound/customqueries.json
- sources/assets/zsh/zshrc
- sources/install/package_ad.sh
This new minor release:
- fixes an issue with neo4j. A downgrade was made because of performance issues faced in Bloodhound (08db2ade11c6463599bfe59738c32635c8e2444a)
- renames the bloodhound custom queries categories (#210)
- changes the color to the comments made in a zsh shell (#211)
> Release 3.1.1

- sources/install/package_base.sh
Install zsh before changing the shell to it.
fixes #223
> fix: install zsh before changing shell

- sources/assets/exegol/entrypoint.sh
- sources/assets/exegol/load_supported_setups.sh
- sources/assets/exegol/start.sh
- sources/install/package_ad.sh
- sources/install/package_base.sh
- sources/install/package_web.sh
Formatting bash variables in uppercase.
> Switch to uppercase bash variables

- sources/install/package_base.sh
Checks if processes are started at the end of the build
> Add a listening process check at the end of the build

- sources/install/package_rfid.sh
temporary fix for proxmark3 not compiling, duh
> temp fix proxmark3

- sources/assets/zsh/history.d/msfconsole
- sources/install/common.sh
- sources/install/package_base.sh
- sources/install/package_c2.sh
cf. PR title, just cleaning things
testing in pipelines before merging
> Mini refacto, cleaning useless functions

- sources/assets/zsh/aliases.d/LDAPWordlistHarvester
- sources/assets/zsh/history.d/LDAPWordlistHarvester
- sources/install/package_ad.sh
Adding [LDAPWordlistHarvester](https://github.com/p0dalirius/LDAPWordlistHarvester)
> Adding LDAPWordlistHarvester

- sources/install/package_most_used.sh
- sources/install/package_web.sh
Installing sslscan from source to solve `openssl` problem
> Installing sslscan from source

- sources/assets/zsh/history.d/pywerview
- sources/install/package_ad.sh
Add https://github.com/the-useless-one/pywerview
> Add pywerview

- sources/assets/zsh/history.d/freeipscanner
- sources/assets/zsh/history.d/scrtdnsdump
- sources/install/package_ad.sh
Addition of https://github.com/scrt/freeipscanner
Addition of https://github.com/scrt/scrtdnsdump in draft
> Add freeipscanner

- sources/install/package_ad.sh
Following https://github.com/dirkjanm/BloodHound.py/pull/146
> Fixing bloodhound.py

- sources/assets/exegol/load_supported_setups.sh
Replaced "$MY_SETUP_PATH/firefox/certs"/* with an equivalent using "find" command so that it does not return an error when there is no user CA in my-resources.
> Added check on existing certs in my-resources before looping.

- sources/assets/shells/aliases.d/empire
- sources/assets/shells/exegol_shells_rc
- sources/assets/shells/history.d/empire
- sources/install/package_ad.sh
- sources/install/package_c2.sh
Adding Empire from https://github.com/BC-SECURITY/Empire
> Add Empire

- sources/install/package_ad.sh
https://github.com/micahvandeusen/gMSADumper/pull/13 has not been merged yet.
> fix(ad): extend temp fix for gmsadumper

- sources/assets/exegol/skel/supported_setups.md
Add information on how to add the configuration for Neovim in the local documentation.
https://github.com/ThePorgs/Exegol-images/pull/283#discussion_r1431898074
> Completion of the local documentation for Neovim

- wifi.dockerfile
> Add WiFi.dockerfile

- sources/install/package_base.sh
latest release does not always contain all expected binaries
fixes #291
> fix: change temurin11 url

- sources/install/package_ad.sh
- sources/install/package_base.sh
- sources/install/package_mobile.sh
- sources/install/package_reverse.sh
Increase temp fix limit (mobsf)
Fix lief version for checksec-py
> Fix checksec-py lief version

- sources/install/package_misc.sh
Edit link to get the latest cyberchef release.
> Get latest cyberchef release

- sources/install/package_c2.sh
> Increase msf temp fix

- sources/assets/shells/aliases.d/metasploit
- sources/install/package_c2.sh
Install and init msfdb (metasploit)
> Install and init msfdb

- sources/assets/bloodhound-ce/bloodhound.config.json
- sources/install/package_ad.sh
Fix bloodhound-ce installation due to a configuration change.
> Fix Bloodhound-ce deployment adding config file

- sources/assets/shells/history.d/asrepcatcher
- sources/install/package_ad.sh
Adding ASRepCatcher tool in AD package
> Adding tool ASRepCatcher

- sources/install/package_web.sh
Greetings,
This PR aims to update Nuclei which right now is in version 2.x to 3.x.
Regards.
N / A
N / A
> Update nuclei to version 3

- sources/install/package_wordlists.sh
Greetings,
If we use `username-anarchy` using a an input file we got:
```
/opt/tools/username-anarchy/username-anarchy:238:in `load_names_list': undefined method `exists?' for File:Class (NoMethodError)
raise "#{filename}: No such file" unless File.exists?(filename)
^^^^^^^^
Did you mean?  exist?
from /opt/tools/username-anarchy/username-anarchy:606:in `<main>'
```
This PR https://github.com/urbanadventurer/username-anarchy/pull/3/files fix the problem but it wasn't merged and probably never will.
My PR aim to apply the fixing PR directly, so one can do:
```bash
username-anarchy -i user.txt
```
Regards.
N /A
N / A
> Fix username-anarchy

- .github/workflows/sub_code_check.yml
- .github/workflows/sub_export_tools.yml
- sources/assets/desktop/applications/burpsuite.desktop
- sources/assets/shells/history.d/asrepcatcher
- sources/assets/shells/history.d/creds
- sources/assets/shells/history.d/nuclei
- sources/code_compliance_check.py
- sources/install/package_ad.sh
- sources/install/package_base.sh
- sources/install/package_c2.sh
- sources/install/package_cracking.sh
- sources/install/package_desktop.sh
- sources/install/package_misc.sh
- sources/install/package_mobile.sh
- sources/install/package_web.sh
- sources/install/package_wifi.sh
- sources/install/package_wordlists.sh
- fixed metasploit missing dependency, BurpSuite bad command in desktop shortcut, nuclei history
- added [asrepcatcher](https://github.com/Yaxxine7/ASRepCatcher), [default creds cheatsheet](https://github.com/ihebski/DefaultCreds-cheat-sheet)
- improved CCC and pipeline
- reduced image size by removing sslscan build files (200MB)
- bumped nuclei to v3
> Release 3.1.4

- sources/assets/shells/history.d/uberfile
The argument `--downloader` doesn't seems to exist, this PR replace the `--downloader` argument with the correct `-d`.
N/A
N/A
> Update uberfile history

- sources/install/package_mobile.sh
- sources/install/package_reverse.sh
Fix checksec & androguard
Pipeline tests
> Fix checksec & androguard

- sources/assets/shells/history.d/faketime
This PR adds an alias for faketime so that it can automatically retrieve the time from the remote server. 
https://github.com/ThePorgs/Development/issues/196
> Add faketime history

- sources/assets/shells/aliases.d/spiderfoot
This PR fixes the spiderfoot alias so that it runs in its source folder so that it can load all of its dependencies.
https://github.com/ThePorgs/Development/issues/193
> Fix spiderfoot alias

- sources/install/package_osint.sh
This PR adds a missing dependency to pwndb.
https://github.com/ThePorgs/Development/issues/187
> Added missing dependency to pwndb

- sources/assets/shells/history.d/katana
- sources/install/package_web.sh
> Add katana tool

- sources/assets/shells/aliases.d/sherlock
- sources/assets/shells/history.d/sherlock
- sources/install/package_osint.sh
Replace sherlock installation from sources with pipx
> Replace sherlock installation from sources with pipx

- sources/assets/shells/history.d/gobuster
Add vhost and dns history for Gobuster
> Update history for Gobuster

- sources/assets/shells/aliases.d/networkIP
- sources/assets/shells/history.d/nmap
Added an alias to copy the IP address of a network interface directly to the clipboard, along with a history of fast UDP scans with Nmap.
> Added Alias and history

- sources/install/package_network.sh
Added call to `install_remmina` function.
#391
> Fix remmina installation

- sources/install/package_web.sh
Editing the `jwt_tool` configuration by disabling the default proxy, and fixing the paths to the wordlist files.
https://github.com/ThePorgs/Exegol-images/issues/392
> Fix jwt_tool configuration

- sources/assets/shells/history.d/gowitness
Gowitness arguments format seems to have changed. This PR aim to fix the history.
N/A
N/A
> Fixed Gowitness history arguments

- sources/install/package_ad.sh
Add missing sha256 to collectors.
closes: #445 
* #445
> Add missing sha256 sum - Bloodhound-CE

- sources/install/package_most_used.sh
Add new tools for the light image :
* Bloodhound legacy
* Neo4j
* Bloodhound.py (ingestor)
* coercer
* ThePorgs/Development#247
> New tools for the light image.

- sources/assets/shells/exegol_shells_rc
- sources/assets/shells/zshrc
Add `/opt/my-resources/bin` in first position in the PATH.
closes: ThePorgs/Development#227
* ThePorgs/Development#227
> Fix PATH order

- sources/install/package_most_used.sh
Add proxychains to light
* ThePorgs/Development#249
> Add proxychains to light

- sources/install/package_misc.sh
Install `yq` and `xq`.
closes: #426 
#426
> New tools - yq / xq

- sources/install/common.sh
- sources/install/package_ad.sh
- sources/install/package_c2.sh
- sources/install/package_cloud.sh
- sources/install/package_code_analysis.sh
- sources/install/package_cracking.sh
- sources/install/package_crypto.sh
- sources/install/package_desktop.sh
- sources/install/package_forensic.sh
- sources/install/package_iot.sh
- sources/install/package_misc.sh
- sources/install/package_mobile.sh
- sources/install/package_most_used.sh
- sources/install/package_network.sh
- sources/install/package_osint.sh
- sources/install/package_reverse.sh
- sources/install/package_rfid.sh
- sources/install/package_sdr.sh
- sources/install/package_steganography.sh
- sources/install/package_voip.sh
- sources/install/package_web.sh
- sources/install/package_wifi.sh
- sources/install/package_wordlists.sh
Just `apt-get update` when needed, also it prevent silly fails when you `fapt something` and you forgot to `apt-get update`.
This is also a step to make #454 work because install steps do not depend on a previous `apt-get update` anymore :)
> perf: only apt-get update when needed

- sources/install/common.sh
On the nightly image:
- /root/.cargo/registry: -844M :rocket::rocket::rocket: 
- /root/.npm/_cacache: -348M :rocket::rocket: 
- /root/.nvm/.cache: -72M :rocket:
- /root/.bundle/cache: -27M :rocket: 
> perf: purge cache between layers

- sources/install/package_c2.sh
- sources/install/package_sdr.sh
- sources/install/package_web.sh
- tls-scanner -175Mo :rocket::rocket::rocket:
- Empire: -67Mo :rocket::rocket:
- Kraken: -400Ko 
> perf: missing git shallow

- sources/dockerfiles/Dockerfile
- sources/dockerfiles/ad.dockerfile
- sources/dockerfiles/light.dockerfile
- sources/dockerfiles/osint.dockerfile
- sources/dockerfiles/web.dockerfile
`RUN apt-get update` just add a useless layer, moreover the apt cache is regenerated before each install and cleaned at the end of each layer...
> perf: useless `apt-get update` layers

- .github/workflows/sub_test.yml
- sources/assets/exegol/build_pipeline_tests/run_tests.py
Because the `/.exegol/build_pipeline_tests/run_tests.py` does not work on published images (do not remove it, I think it can be useful to check if everything work well).
And it will be useful for #454 :)
> chore: move test sort in `run_tests.py`

- sources/assets/shells/aliases.d/finduncommonshares
- sources/install/package_ad.sh
FindUncommonShares was recently renamed (https://github.com/p0dalirius/pyFindUncommonShares/issues/34)
> fix: pyFindUncommonShares was renamed

- sources/assets/shells/aliases.d/exegol-history
- sources/assets/shells/zshrc
This PR aims to fix the history alias.
N / A
N / A
> Fix history

- sources/install/package_ad.sh
- sources/install/package_cracking.sh
- sources/install/package_desktop.sh
- sources/install/package_misc.sh
- sources/install/package_network.sh
- sources/install/package_rfid.sh
- sources/install/package_sdr.sh
- sources/install/package_web.sh
- sources/install/package_wifi.sh
`make -j` allow parallel compilation + you can `make clean` after a `make install` :)
> perf: prefer `make -j` and `make clean` when possible 

- sources/assets/shells/zshrc
The git plugin was installed but not used... It adds a whole set of aliases for mastering git!
Here the full list of git aliases: https://kapeli.com/cheat_sheets/Oh-My-Zsh_Git.docset/Contents/Resources/Documents/index
> ohmyzsh git plugin

- sources/assets/shells/history.d/gitleaks
- sources/assets/shells/history.d/trufflehog
- sources/install/package_code_analysis.sh
> These two tools have both their own strenghts and weaknesses:
> 
>   -  TruffleHog is very effective at classifying different secrets, but cannot find them all. It relies on detectors that can easily detect specific types of secrets, but not general secrets or general API keys.
>   -  Gitleaks is able to find many more secrets, but is not as good as Trufflehog at classification. It contains fewer detectors and relies on string entropy to detect potential secrets that are not found by its detectors.
>
> *Sources: https://github.com/padok-team/git-secret-scanner?tab=readme-ov-file#why-this-tool*
> Secret finders
